name: Rust

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  audit:
    name: Audit Rust vulnerabilities
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-audit
        use-tool-cache: true

    - run: cargo audit

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose

      - name: clean
        uses: actions-rs/cargo@v1
        with:
          command: clean

      - name: lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D warnings
